### PR TITLE
Added feature to show the remaining time in the progress bar

### PR DESCRIPTION
**Pull request by richardkopelow**
There is a setting in the settings tab that will cause the remaining time it will take to finish the text to be shown in the progress bar.

### CODE REVIEW

**Comment by anthonynosek** [comment]
Thanks @richardkopelow. When I have a chance I will test and merge your changes into the branch. Just short on time at the moment but will do it as soon as I can.

Are you working on any other features?
Would you like to?

**Comment by richardkopelow** [comment]
It seems I was a little premature with submitting this pull request. I forgot to hook it up to the Defaults button so the setting gets reset. I should have that committed in a few minutes.

I am also working on the flicker feature #7 request.

**Comment by anthonynosek** [comment]
No stress, I appreciate your help. Like I said- I'll compile everything for a new release once you are satisfied that you've completed the work you intended to... and I find the time to do it.

Cheers

**Comment by richardkopelow** [comment]
@anthonynosek I finished the work I'm planing to get done soon. Feel free to compile it together whenever you get a chance.

**Pull request merged**
